version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Novosibirsk
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:15"
      timezone: Asia/Novosibirsk
    open-pull-requests-limit: 5
